In [6]:
import numpy as np

In [7]:
a=[[1,2,3],
   [4,5,6],
   [7,8,9]]

b=[[0,0,0],
   [0,0,0],
   [0,0,0]]

In [8]:
# 두 배열을 수평으로 결합
result = np.concatenate((a, b), axis=1)

In [9]:
print(result)

[[1 2 3 0 0 0]
 [4 5 6 0 0 0]
 [7 8 9 0 0 0]]
