In [1]:
import numpy as np

In [15]:
a=[[1,2,3],
   [4,5,6],
   [7,8,9]]

b=[[0,0,0],
   [0,0,0],
   [0,0,0]]

In [16]:
# 두 배열을 수평으로 결합
result = np.concatenate((a, b), axis=1)

In [17]:
print(result)

[[1 2 3 0 0 0]
 [4 5 6 0 0 0]
 [7 8 9 0 0 0]]


In [18]:
a=[[1,2,3],
   [4,5,6],
   [7,8,9]]

In [19]:
a = np.array(a)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
a=[[1,2,3,4,5],
   [4,5,6],
   [7,8,9],
   [7,8,9],]

In [8]:
a = np.array(a)
print(a)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.